name: VERIFICAR ARCHIVOS DE CONFIGURACIÓN

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  verify-files:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar tu código (Checkout)
        uses: actions/checkout@v4

      - name: "----------------------------------------------------"
        run: echo "PASO 1: VERIFICANDO EL ARCHIVO BUILDOZER.SPEC"

      - name: Mostrar contenido de buildozer.spec
        run: cat buildozer.spec

      - name: "----------------------------------------------------"
        run: echo "PASO 2: VERIFICANDO EL ARCHIVO DE WORKFLOW (.YML)"
      
      - name: Listar archivos en .github/workflows
        run: ls -l .github/workflows/

      - name: Mostrar contenido del archivo YML
        # IMPORTANTE: Si tu archivo no se llama 'main.yml', cambia el nombre en la línea de abajo
        run: cat .github/workflows/main.yml

      - name: "----------------------------------------------------"
        run: echo "VERIFICACIÓN COMPLETA. Revisa el contenido de los archivos en el log de esta ejecución."
