name: VERIFICAR ARCHIVOS
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Mostrar buildozer.spec
        run: cat buildozer.spec

      - name: Mostrar archivo yml
        run: cat .github/workflows/build.yml
